language: cpp
compiler:
    - clang
    - gcc
env: FL_CONF=Release REAL_CC=gcc REAL_CXX=g++ EXTRA_DEF=-std=c++11
script
    - export CC=$REAL_CC
    - export CXX=$REAL_CXX
    - mkdir -p $FL_CONF
    - cd $FL_CONF
    - cmake .. -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=$FL_CONF -DEXTRA_DEF=$EXTRA_DEF
    - make -j2
    - make test ARGS="-VV"

