language: cpp

sudo: false

compiler:
    - clang
    - gcc

addons:
    apt:
        sources:
            - boost-latest
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - libboost1.55-all-dev
            - liblua5.1-0-dev
            - lua5.1
            - luarocks
            - rubygems
            - cmake

cache:
    - apt

before_script:
    - echo before

install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test

