sudo: none
dist: trusty

language: generic
cache:
  - ccache
  - pip
matrix:
  include:
    - os:
        - linux
        - osx
      env:
        - COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5 MODE=Debug
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os:
        - linux
        - osx
      env:
        - COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8 MODE=Debug
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources
    - os:
        - linux
        - osx
      env:
        - COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5 MODE=Release
      addons:
        apt:
          packages:
            - g++-5
          sources: *sources
    - os:
        - linux
        - osx
      env:
        - COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8 MODE=Release
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources

install:
  - pip install --user pyyaml
  - pip install --user poster

script:
  - (cd cmaki && git pull origin master)
  - (cd cmaki_generator && git pull origin master)
  - ./cmaki/run.sh $MODE
  - echo TRAVIS_REPO_SLUG=github://$TRAVIS_REPO_SLUG
  - |
    if [[ $CXX == "g++" && $MODE == "Release" ]]; then
        (cd cmaki_generator && ./build fast-event-system --server=http://artifacts.myftp.biz:8080)
    fi
