sudo: none
dist: trusty

language: c
cache:
  - ccache
  - pip

compiler:
  - clang
  - gcc

env:
  - MODE=Debug
  - MODE=Release

install:
  - pip install --user pyyaml
  - pip install --user poster

script:
  - (cd cmaki && git pull origin master)
  - (cd cmaki_generator && git pull origin master)
  - ./cmaki/run.sh $MODE
  - echo TRAVIS_REPO_SLUG=github://$TRAVIS_REPO_SLUG
  - |
    if [[ $CXX == "g++-4.9" && $MODE == "Release" ]]; then
        (cd cmaki_generator && ./build fast-event-system --server=http://artifacts.myftp.biz:8080)
    fi
