title: Fast event system
email: makiolo@gmail.com
description: >
    fes blog
baseurl: "/blog"
url: "http://makiolo.github.io/fast-event-system"
twitter_username: makiolo
github_username:  makiolo
markdown: kramdown

